### ISSUE TITLE
Apresentação

### ISSUE THREAD

**Issue by fsantanna** [HandelSM/Ceu-arduino#1]
Boa Handel!
Algumas sugestões:
- Usar uma fonte mono espaçada. É muito ruim ler código com a fonte que você colocou.
- Usar o mesmo número de espaços na indentação para C e Céu
- Marcar as palavras reservadas de C e Céu em bold (manualmente mesmo, uma a uma). Isso ajuda muito na legibilidade do slide.
- Incluir algum slide de apoio em tópicos antes de cada código pra lembrar o objetivo de mostrá-lo.
- Em C, colocando as chaves na linha de cima, você ganha uma linha:

```
if (cond)
{
    <...>
}
```

```
if (cond) {
    <...>
}
```

**Comment by fsantanna** [comment]
A fonte continua esquisita.
Não entendi o seu esquema de cores também.

**Comment by fsantanna** [comment]
Outra coisa, tem um exemplo em C com uns Serial.print, mas o em céu não tem

**Comment by HandelSM** [comment]
Tirarei os prints.
As cores eu usei as do editor de texto mesmo.
E sobre a fonte você tem alguma sugestão? Eu teria usado a mesma que você
usa em seus slides, porém não tinha como opção no Power Point, vou procurar
no libre office.

Outra coisa, não sei porque mas não tá funcionando o código, eu fiquei
debugando hoje de manhã mas ainda não consegui descobrir o problema, vou
tentar solucionar tudo isso até a aula. Penso se é possível ser o problema
da pilha estourando...

**Comment by fsantanna** [comment]
Qualquer fonte "monospaced". Com certeza o powerpoint tem alguma.

Se o código já funcionou e você não mudou nada, não tem porque ter algum problema nele.

**Comment by fsantanna** [comment]
O seu editor não suporta Céu, então o esquema de cores não está fazendo muito sentido.

**Comment by fsantanna** [comment]
Se não conseguir mesmo, você tem um vídeo?

**Comment by HandelSM** [comment]
Sim, eu tava testando os componentes separadamente, não estava debugando o
código, mas sim o circuito.

**Comment by HandelSM** [comment]
Tenho, mas eu posso rodar o código de C, tbm é uma opção

**Comment by fsantanna** [comment]
Valeu Handel. Ficou legal.
